#Echo configuration file.
#You must put your Echo API key.
#If you don't have an enterprise plan, freeze command will not work.

SERVER_API_KEY: "" #This is the API key that console uses. Only 1 concurrent scan can be run at a time on this API key.

NO_PERMISSION: "&cNo permission"

ALTS_COMMAND:
  ENABLED: true
  NOT_ALTS_MESSAGE: "&cCouldn't find any alts"
  START_MESSAGE: "Searching Echo for aliases of {player}..." #Placeholders: {player}
  FINISH_MESSAGE: "{alts}" #Placeholders: {alts}
FREEZE_COMMAND:
  ENABLED: true
  PLAYER_MOVE_EVENT: true #Disable this if you have players getting disconnected/anti-crash kicking them while frozen
  MESSAGE: "&c&lYou are frozen!&c You have {countdown} seconds to run this: {link}" #Placeholders: {player}, {countdown}
  SEND_MESSAGE_EVERY: 5000 #integer in milliseconds to send the freeze message (default: every 5 seconds)
  STAFF_STARTED_MESSAGE: "&a&lStarted! &a{player} has downloaded and ran echo, now scanning!"
  STAFF_RESULT_MESSAGE: "&a&lScan complete! &aResults: {link}" #Placeholders: {link}
  AUTOBAN:
    ENABLED: true
    TIME_BEFORE_AUTOBAN: 300000 #integer in milliseconds before automatic ban (default: 5 minutes)
    AUTOBAN_COMMAND: "/ban {player} Refusal to SS" #Placeholders: {player}
    AUTOBAN_COMMAND_CONSOLE: false #True = will send command thru console | False = will send command thru whoever the dispatched command.
ECHO_COMMAND:
  ENABLED: true