name: Echo
version: ${echo.desc}
description: Echo Screenshare Tool Plugin
main: ac.echo.Echo
author: [Cow, Josh]
commands:
  alts:
    description: Show known aliases
    usage: /alts
  freeze:
    description: Freezes a player
    usage: /freeze
  echo:
    description: Get information about Echo
    usage: /echo